[mypy]
python_version = 3.9
strict = True

[mypy-uproot]
ignore_missing_imports = True

[mypy-uproot.*]
ignore_missing_imports = True

[mypy-awkward]
ignore_missing_imports = True

[mypy-awkward.*]
ignore_missing_imports = True
